name: Deploy VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 191.252.205.40
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo -u deploy /var/www/deploy.sh
            cd /var/www/portaldeaplicativos && git log -1 --format="%h (%cd)" --date=format:"%d/%m %H:%M" > .version